---
- hosts: all
  sudo: yes

  vars_files:
    - vars/defaults.yml

  roles:
    - webserver
    - database
    - nagios

  handlers:
    - name: restart puma
      service: name=puma state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart nagios
      service: name=nagios3 state=restarted

    - name: restart db
      service: name=postgresql state=restart

