---
- hosts: all
  sudo: yes

  vars_files:
    - vars/defaults.yml

  roles:
    - { role: webserver, tags: [webserver] }
    - { role: database, tags: [database] }
    - { role: nagios, tags: [nagios] }

  handlers:
    - name: restart puma-manager
      service: name=puma-manager state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart nagios
      service: name=nagios3 state=restarted

    - name: restart db
      service: name=postgresql state=restart

