---
- hosts: all
  sudo: yes

  vars_files:
    - vars/defaults.yml

  roles:
    - webserver
    - database
    - nagios

  handlers:
    - name: restart puma
      action: service name=puma state=restarted

